/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaranlomba;

/**
 *
 * @author Kelvin Wilson Utomo
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGame = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jButtonDiterima = new javax.swing.JButton();
        jButtonPending = new javax.swing.JButton();
        jButtonDitolak = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonBracketTeam = new javax.swing.JButton();
        jButtonBracketIndiv = new javax.swing.JButton();
        jButtonOngoingMatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Pilih Menu");

        jButtonGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonGame.setText("List Game");
        jButtonGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGameActionPerformed(evt);
            }
        });

        jButtonAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAdmin.setText("List Admin");
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });

        jButtonDiterima.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDiterima.setText("List Peserta Diterima");
        jButtonDiterima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiterimaActionPerformed(evt);
            }
        });

        jButtonPending.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPending.setText("List Peserta Pending");
        jButtonPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPendingActionPerformed(evt);
            }
        });

        jButtonDitolak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDitolak.setText("List Peserta Ditolak");
        jButtonDitolak.setToolTipText("");
        jButtonDitolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDitolakActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonBracketTeam.setText("Bracket Team");
        jButtonBracketTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBracketTeamActionPerformed(evt);
            }
        });

        jButtonBracketIndiv.setText("Bracket Indiv");
        jButtonBracketIndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBracketIndivActionPerformed(evt);
            }
        });

        jButtonOngoingMatch.setText("Ongoing Match");
        jButtonOngoingMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOngoingMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonDiterima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jButtonPending, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDitolak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonBracketTeam, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(jButtonBracketIndiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonOngoingMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 397, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGame, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDiterima, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDitolak, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPending, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBracketTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonBracketIndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOngoingMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPendingActionPerformed
        // TODO add your handling code here:
         listPending game = new listPending();
        String[] args = {};
        game.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPendingActionPerformed

    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
        listAdmin game = new listAdmin();
        String[] args = {};
        game.main(args);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdminActionPerformed

    private void jButtonGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGameActionPerformed
        // TODO add your handling code here:
        listGame game = new listGame();
        String[] args = {};
        game.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGameActionPerformed

    private void jButtonDiterimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiterimaActionPerformed
        // TODO add your handling code here:
           listPeserta game = new listPeserta();
        String[] args = {};
        game.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDiterimaActionPerformed

    private void jButtonDitolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDitolakActionPerformed
        // TODO add your handling code here:
        listTolak game = new listTolak();
        String[] args = {};
        game.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDitolakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
          login game = new login();
        String[] args = {};
        game.main(args); 
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBracketTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBracketTeamActionPerformed
        // TODO add your handling code here:
             dispose();
          BracketTeam game = new BracketTeam();
        String[] args = {};
        game.main(args); 
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBracketTeamActionPerformed

    private void jButtonBracketIndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBracketIndivActionPerformed
        // TODO add your handling code here:
                 dispose();
          BracketIndiv game = new BracketIndiv();
        String[] args = {};
        game.main(args); 
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBracketIndivActionPerformed

    private void jButtonOngoingMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOngoingMatchActionPerformed
        // TODO add your handling code here:
             dispose();
          ongoingMatch game = new ongoingMatch();
        String[] args = {};
        game.main(args); 
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOngoingMatchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonBracketIndiv;
    private javax.swing.JButton jButtonBracketTeam;
    private javax.swing.JButton jButtonDiterima;
    private javax.swing.JButton jButtonDitolak;
    private javax.swing.JButton jButtonGame;
    private javax.swing.JButton jButtonOngoingMatch;
    private javax.swing.JButton jButtonPending;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
