/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pendaftaranlomba;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author ROG ZEPHYRUS
 */
public class BracketTeam extends javax.swing.JFrame {
    private DefaultTableModel tableModel2;
      private DefaultTableModel tableModel1;
      
public String idteam;
public String idteam1;

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
    int selectedRow = jTablePesertaTeam.getSelectedRow(); 
    idteam1 = jTablePesertaTeam1.getValueAt(selectedRow, 5).toString();
    idteam = jTablePesertaTeam.getValueAt(selectedRow, 5).toString();
}



    /**
     * Creates new form BracketTeam
     */
    public BracketTeam() {
        initComponents();
    tableModel2 = (DefaultTableModel) jTablePesertaTeam.getModel();
     tableModel1 = (DefaultTableModel) jTablePesertaTeam1.getModel();
  
      jTablePesertaTeam1.addMouseListener(new java.awt.event.MouseAdapter() {
          
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = jTablePesertaTeam1.getSelectedRow();
            idteam1 = jTablePesertaTeam1.getValueAt(selectedRow, 5).toString();
               System.out.println("ID Team2: " + idteam1);
        }
    });
    
      jTablePesertaTeam.addMouseListener(new java.awt.event.MouseAdapter() {
          
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = jTablePesertaTeam.getSelectedRow();
            idteam = jTablePesertaTeam.getValueAt(selectedRow, 5).toString();

            System.out.println("ID Team: " + idteam);

        }
    });
    }
           public void viewPesertaTeam(JSONArray jsonArray) {
         tableModel2.setRowCount(0);
         tableModel1.setRowCount(0);
        String kondisi ="";
        for (Object object : jsonArray) {
            JSONObject data = (JSONObject) object;
            String nama_team = (String) data.get("nama_team");
            String nama_game = (String) data.get("nama_game");
            Long win = (Long) data.get("win");
            Long lose = (Long) data.get("lose");
              Long status = (Long) data.get("status");
              Long idteam = (Long) data.get("idteam");
            if (status == 0) {
                  kondisi = "pending";
              } else if (status == 1) {
                  kondisi = "Diterima";
              } else {
                  kondisi = "ditolak";
              }
            Object[] rowData = {nama_team,nama_game,win,lose,kondisi,idteam};
            tableModel2.addRow(rowData);
             tableModel1.addRow(rowData);
        }
         jTablePesertaTeam.setModel(tableModel2);
            jTablePesertaTeam1.setModel(tableModel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesertaTeam = new javax.swing.JTable();
        jButtonBracketTeam = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePesertaTeam1 = new javax.swing.JTable();
        jTextFieldTanggalBracket = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Daftar Team");

        jTablePesertaTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Team", "Nama Game", "Win", "Lose", "Status", "Id Team"
            }
        ));
        jScrollPane2.setViewportView(jTablePesertaTeam);

        jButtonBracketTeam.setText("Tandingkan");
        jButtonBracketTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBracketTeamActionPerformed(evt);
            }
        });

        jTablePesertaTeam1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Team", "Nama Game", "Win", "Lose", "Status", "Id Team"
            }
        ));
        jScrollPane3.setViewportView(jTablePesertaTeam1);

        jLabel1.setText("Tanggal");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextFieldTanggalBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtonBracketTeam)
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBracketTeam)
                    .addComponent(jTextFieldTanggalBracket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBracketTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBracketTeamActionPerformed
        // TODO add your handling code here:
            String url = "http://localhost:7000/insertBracketTeam";
    String date = jTextFieldTanggalBracket.getText();
    String postData = "{\"idteam\": " + idteam + ", \"idteam1\": " + idteam1 + ", \"date\": \"" + date + "\"}";

                try {
                            
                    URL obj = new URL(url);
                    HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                    // Set the request method to POST
                    con.setRequestMethod("POST");

                    // Set the request headers
                    con.setRequestProperty("Content-Type", "application/json");

                    // Enable the output stream and write the POST data
                    con.setDoOutput(true);
                    OutputStream os = con.getOutputStream();
                    os.write(postData.getBytes());
                    os.flush();
                    os.close();

                    // Get the response from the server (if needed)
                    int responseCode = con.getResponseCode();
                    BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                    String inputLine;
                    StringBuilder response = new StringBuilder();
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();

                    // Handle the response (if needed)
                    System.out.println(response.toString());

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
            try {
            listPending form = new listPending();
            
      
            String url2 = "http://localhost:7000/TeamDiterima";

      
            URL obj = new URL(url2);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");

        
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");



            if (jsonArray.size() > 0) {
               form.viewPesertaTeam(jsonArray); 
             

             viewPesertaTeam(jsonArray);
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBracketTeamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        index game = new index();
        String[] args = {};
        game.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          BracketTeam form = new BracketTeam();
        try {
     

            String url = "http://localhost:7000/TeamDiterima";

            // Buat objek URL dan HttpURLConnection
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");


            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
      
            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");


            if (jsonArray.size() > 0) {
               form.viewPesertaTeam(jsonArray); 
   
          
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BracketTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BracketTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BracketTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BracketTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBracketTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePesertaTeam;
    private javax.swing.JTable jTablePesertaTeam1;
    private javax.swing.JTextField jTextFieldTanggalBracket;
    // End of variables declaration//GEN-END:variables
}
