/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaranlomba;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Kelvin Wilson Utomo
 */
public class listPending extends javax.swing.JFrame {
  
private DefaultTableModel tableModel;
private DefaultTableModel tableModel2;
    /**
     * Creates new form listPending
     */

public String idpeserta;
public String idteam;


private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
    int selectedRow = jTablePesertaIndiv.getSelectedRow(); 
    idpeserta = jTablePesertaIndiv.getValueAt(selectedRow, 11).toString();
    idteam = jTablePesertaTeam.getValueAt(selectedRow, 5).toString();
}
    public listPending() {
         initComponents();
    tableModel = (DefaultTableModel) jTablePesertaIndiv.getModel();
    tableModel2 = (DefaultTableModel) jTablePesertaTeam.getModel();
        
    jTablePesertaIndiv.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = jTablePesertaIndiv.getSelectedRow();
            idpeserta = jTablePesertaIndiv.getValueAt(selectedRow, 11).toString();
            System.out.println("ID Peserta: " + idpeserta);
        }
    });
    
      jTablePesertaTeam.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = jTablePesertaTeam.getSelectedRow();
            idteam = jTablePesertaTeam.getValueAt(selectedRow, 5).toString();
            System.out.println("ID Team: " + idteam);
        }
    });
      
    }
 public void viewPesertaIndiv(JSONArray jsonArray) {
         tableModel.setRowCount(0);
String kondisi ="";
        for (Object object : jsonArray) {
            JSONObject data = (JSONObject) object;
            String nama = (String) data.get("nama");
            String alamat = (String) data.get("alamat");
            String tanggal_lahir = (String) data.get("tanggal_lahir");
            String no_handphone = (String) data.get("no_handphone");
            String nrp = (String) data.get("nrp");
            String program_studi = (String) data.get("program_studi");
            String angkatan = (String) data.get("angkatan");
            Long win = (Long) data.get("win");
            Long lose = (Long) data.get("lose");
            String game = (String) data.get("nama_game");
            Long status = (Long) data.get("status");
            Long idPeserta = (Long) data.get("idpeserta");
            if (status == 0) {
                  kondisi = "pending";
              } else if (status == 1) {
                  kondisi = "Diterima";
              } else {
                  kondisi = "ditolak";
              }
            
            Object[] rowData = {nama,alamat,tanggal_lahir,no_handphone,nrp,program_studi,angkatan,game,win,lose,kondisi,idPeserta};
            tableModel.addRow(rowData);
        }
         jTablePesertaIndiv.setModel(tableModel);
    }
       
         public void viewPesertaTeam(JSONArray jsonArray) {
         tableModel2.setRowCount(0);
        String kondisi ="";
        for (Object object : jsonArray) {
            JSONObject data = (JSONObject) object;
            String nama_team = (String) data.get("nama_team");
            String nama_game = (String) data.get("nama_game");
            Long win = (Long) data.get("win");
            Long lose = (Long) data.get("lose");
              Long status = (Long) data.get("status");
              Long idteam = (Long) data.get("idteam");
            if (status == 0) {
                  kondisi = "pending";
              } else if (status == 1) {
                  kondisi = "Diterima";
              } else {
                  kondisi = "ditolak";
              }
            Object[] rowData = {nama_team,nama_game,win,lose,kondisi,idteam};
            tableModel2.addRow(rowData);
        }
         jTablePesertaTeam.setModel(tableModel2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePesertaTeam = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesertaIndiv = new javax.swing.JTable();
        jButtonTolak = new javax.swing.JButton();
        jButtonTerima = new javax.swing.JButton();
        jButtonTolakTeam = new javax.swing.JButton();
        jButtonTerimaTeam = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Daftar Pending");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Daftar Team");

        jTablePesertaTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Team", "Nama Game", "Win", "Lose", "Status", "Id Team"
            }
        ));
        jScrollPane2.setViewportView(jTablePesertaTeam);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Daftar Peserta Individu");

        jTablePesertaIndiv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Peserta", "Alamat", "Tanggal Lahir", "No Telfon", "NRP", "Program Studi", "Angkatan", "Nama Game", "Win", "Lose", "Status", "idPeserta"
            }
        ));
        jScrollPane1.setViewportView(jTablePesertaIndiv);

        jButtonTolak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTolak.setForeground(new java.awt.Color(255, 0, 51));
        jButtonTolak.setText("Tolak");
        jButtonTolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTolakActionPerformed(evt);
            }
        });

        jButtonTerima.setBackground(new java.awt.Color(153, 255, 153));
        jButtonTerima.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTerima.setForeground(new java.awt.Color(51, 204, 0));
        jButtonTerima.setText("Terima");
        jButtonTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerimaActionPerformed(evt);
            }
        });

        jButtonTolakTeam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTolakTeam.setForeground(new java.awt.Color(255, 0, 51));
        jButtonTolakTeam.setText("Tolak");
        jButtonTolakTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTolakTeamActionPerformed(evt);
            }
        });

        jButtonTerimaTeam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTerimaTeam.setForeground(new java.awt.Color(51, 255, 0));
        jButtonTerimaTeam.setText("Terima");
        jButtonTerimaTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerimaTeamActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(43, 43, 43)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(299, 299, 299))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonTolak, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonTolakTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonTerimaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(262, 262, 262)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTerima, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTolak, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTerimaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTolakTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTolakActionPerformed
        // TODO add your handling code here:
             String url = "http://localhost:7000/updateTolakPeserta";
                String postData = "{\"idpeserta\": " + idpeserta + "}";
                try {
                       
                    URL obj = new URL(url);
                    HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                    // Set the request method to POST
                    con.setRequestMethod("POST");

                    // Set the request headers
                    con.setRequestProperty("Content-Type", "application/json");

                    // Enable the output stream and write the POST data
                    con.setDoOutput(true);
                    OutputStream os = con.getOutputStream();
                    os.write(postData.getBytes());
                    os.flush();
                    os.close();

                    // Get the response from the server (if needed)
                    int responseCode = con.getResponseCode();
                    BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                    String inputLine;
                    StringBuilder response = new StringBuilder();
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();

                    // Handle the response (if needed)
                    System.out.println(response.toString());

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                  try {
     listPending form = new listPending();
            
      
            String url2 = "http://localhost:7000/PesertaGameIndividuPending";

      
            URL obj = new URL(url2);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");

        
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");



            if (jsonArray.size() > 0) {
               form.viewPesertaIndiv(jsonArray); 
             

           viewPesertaIndiv(jsonArray);
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTolakActionPerformed

    private void jButtonTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerimaActionPerformed
        // TODO add your handling code here:    
             String url = "http://localhost:7000/updateStatusDiterima";
                String postData = "{\"idpeserta\": " + idpeserta + "}";
                try {
                       
                    URL obj = new URL(url);
                    HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                    // Set the request method to POST
                    con.setRequestMethod("POST");

                    // Set the request headers
                    con.setRequestProperty("Content-Type", "application/json");

                    // Enable the output stream and write the POST data
                    con.setDoOutput(true);
                    OutputStream os = con.getOutputStream();
                    os.write(postData.getBytes());
                    os.flush();
                    os.close();

                    // Get the response from the server (if needed)
                    int responseCode = con.getResponseCode();
                    BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                    String inputLine;
                    StringBuilder response = new StringBuilder();
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();

                    // Handle the response (if needed)
                    System.out.println(response.toString());

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                  try {
     listPending form = new listPending();
            
      
            String url2 = "http://localhost:7000/PesertaGameIndividuPending";

      
            URL obj = new URL(url2);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");

        
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");



            if (jsonArray.size() > 0) {
               form.viewPesertaIndiv(jsonArray); 
             

           viewPesertaIndiv(jsonArray);
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTerimaActionPerformed

    private void jButtonTolakTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTolakTeamActionPerformed
        // TODO add your handling code here:
        
        String url = "http://localhost:7000/updateStatusTeamDitolak";
                String postData = "{\"idteam\": " + idteam + "}";
                try {
                            
                    URL obj = new URL(url);
                    HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                    // Set the request method to POST
                    con.setRequestMethod("POST");

                    // Set the request headers
                    con.setRequestProperty("Content-Type", "application/json");

                    // Enable the output stream and write the POST data
                    con.setDoOutput(true);
                    OutputStream os = con.getOutputStream();
                    os.write(postData.getBytes());
                    os.flush();
                    os.close();

                    // Get the response from the server (if needed)
                    int responseCode = con.getResponseCode();
                    BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                    String inputLine;
                    StringBuilder response = new StringBuilder();
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();

                    // Handle the response (if needed)
                    System.out.println(response.toString());

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                  try {
            listPending form = new listPending();
            
      
            String url2 = "http://localhost:7000/teamPending";

      
            URL obj = new URL(url2);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");

        
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");



            if (jsonArray.size() > 0) {
               form.viewPesertaIndiv(jsonArray); 
             

           viewPesertaTeam(jsonArray);
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTolakTeamActionPerformed

    private void jButtonTerimaTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerimaTeamActionPerformed
    
        String url = "http://localhost:7000/updateStatusTeamDiterima";
                String postData = "{\"idteam\": " + idteam + "}";
                try {
                            
                    URL obj = new URL(url);
                    HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                    // Set the request method to POST
                    con.setRequestMethod("POST");

                    // Set the request headers
                    con.setRequestProperty("Content-Type", "application/json");

                    // Enable the output stream and write the POST data
                    con.setDoOutput(true);
                    OutputStream os = con.getOutputStream();
                    os.write(postData.getBytes());
                    os.flush();
                    os.close();

                    // Get the response from the server (if needed)
                    int responseCode = con.getResponseCode();
                    BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
                    String inputLine;
                    StringBuilder response = new StringBuilder();
                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();

                    // Handle the response (if needed)
                    System.out.println(response.toString());

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                
                  try {
            listPending form = new listPending();
            
      
            String url2 = "http://localhost:7000/teamPending";

      
            URL obj = new URL(url2);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");

        
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");



            if (jsonArray.size() > 0) {
               form.viewPesertaIndiv(jsonArray); 
             

           viewPesertaTeam(jsonArray);
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTerimaTeamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    dispose();
          index game = new index();
        String[] args = {};
        game.main(args);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       listPending form = new listPending();
        try {
     

            String url = "http://localhost:7000/PesertaGameIndividuPending";

            // Buat objek URL dan HttpURLConnection
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");


            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
      
            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");


            if (jsonArray.size() > 0) {
               form.viewPesertaIndiv(jsonArray); 
   
          
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
          try {
     

            String url2 = "http://localhost:7000/teamPending";

            // Buat objek URL dan HttpURLConnection
            URL obj = new URL(url2);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");


            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
      
            System.out.println(response.toString());
            
            JSONParser parser = new JSONParser();
            JSONObject jsonObject = (JSONObject) parser.parse(response.toString());
            JSONArray jsonArray = (JSONArray) jsonObject.get("response");


            if (jsonArray.size() > 0) {
               form.viewPesertaTeam(jsonArray); 
   
          
            } else {
                System.out.println("No data found.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
                    form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTerima;
    private javax.swing.JButton jButtonTerimaTeam;
    private javax.swing.JButton jButtonTolak;
    private javax.swing.JButton jButtonTolakTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePesertaIndiv;
    private javax.swing.JTable jTablePesertaTeam;
    // End of variables declaration//GEN-END:variables
}
